-- login as redenvelope
USE `redenvelope`;

DROP TABLE IF EXISTS `ENVELOPE`;
DROP TABLE IF EXISTS `EVENT`;
DROP TABLE IF EXISTS `USER_FRIEND`;
DROP TABLE IF EXISTS `USER`;

-- USER TABLE
CREATE TABLE `USER` (
  `USER_ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `PASSWORD` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `BALANCE` decimal(11,2) unsigned NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `uk_username` (`USERNAME`),
  KEY `index_credentials` (`PASSWORD`,`USERNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- USER FRIENDS TABLE
CREATE TABLE `USER_FRIEND` (
  `USER_ID` int(11) unsigned NOT NULL,
  `FRIEND_ID` int(11) unsigned NOT NULL,
  PRIMARY KEY (`USER_ID`,`FRIEND_ID`),
  KEY `user_to_friend` (`FRIEND_ID`),
  CONSTRAINT `user_to_friend` FOREIGN KEY (`FRIEND_ID`) REFERENCES `USER` (`USER_ID`),
  CONSTRAINT `user_to_user` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- EVENT TABLE
CREATE TABLE `EVENT` (
  `EVENT_ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) unsigned NOT NULL,
  `AMOUNT` decimal(11,2) NOT NULL,
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `SIZE` int(11) unsigned NOT NULL,
  `ACTIVE_IND` varchar(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`EVENT_ID`),
  KEY `index_active_user_event` (`USER_ID`,`ACTIVE_IND`),
  CONSTRAINT `event_to_user` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ENVELOPE TABLE
CREATE TABLE `ENVELOPE` (
  `ENVELOPE_ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `EVENT_ID` int(11) unsigned NOT NULL,
  `USER_ID` int(11) unsigned DEFAULT NULL,
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `AMOUNT` decimal(11,2) NOT NULL,
  PRIMARY KEY (`ENVELOPE_ID`),
  KEY `envelope_to_user` (`USER_ID`),
  KEY `envelope_to_event` (`EVENT_ID`),
  CONSTRAINT `envelope_to_event` FOREIGN KEY (`EVENT_ID`) REFERENCES `EVENT` (`EVENT_ID`),
  CONSTRAINT `envelope_to_user` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;